### ISSUE TITLE
Net Client

### ISSUE THREAD

**Issue by joseigbintuitivo** [supervisely/agent#27]
Hello! I'm trying to run an agent in an aws instance but the sly-net-client keeps restarting. When I look at the logs of the container I see this:

`/app/entrypoint.sh: line 7: 3: unbound variable`

I tried with another instance and the error keeps the same. I never had this issue before (I've been using supervisely for about 4 months), so I think that has to do with a recent update.

Thank you!

**Comment by tonybart1337** [comment]
thank you for the report. it has been resolved in the latest version of the Supervisely NET client, please redeploy your agent.
