### ISSUE TITLE
Windows with docker?

### ISSUE THREAD

**Issue by mileseverett** [supervisely/agent#33]
Would this work on a windows machine with docker installed? Or does the host need to be linux?

**Comment by TheoLisin** [comment]
Hi, @mileseverett
The agent has not been tested on Windows, however it works flawlessly with WSL 2.

**Comment by mkolomeychenko** [comment]
Please, follow this guide https://developer.supervisely.com/getting-started/connect-your-computer/gpu-agent-wsl-installation
